- name: variables from task level
  hosts: node
  vars:
    NAME: "Naveen"
    AGE: 23
  tasks:
  - name: print inside node
    vars:
      AGE: 18
    ansible.builtin.debug:
      msg: "I'm {{NAME}} with Age:{{AGE}}"