- name: variables from prompt
  hosts: node
  vars_prompt:
  - name: NAME
    prompt: Enter NAME
    private: false
  - name: AGE
    prompt: Enter AGE
    private: true
  tasks:
  - name: print inside node
    ansible.builtin.debug:
      msg: "I'm {{NAME}} with Age:{{AGE}}"